---
name: silverstripe-foxy-discounts-config
---
Dynamic\Foxy\Model\Setting:
  extensions:
    - Dynamic\Foxy\Discounts\Extension\FoxyAdminExtension

Dynamic\Products\Page\Product:
  extensions:
    - Dynamic\Foxy\Discounts\Extension\ProductDataExtension

PageController:
  extensions:
    - Dynamic\Foxy\Discounts\Extension\PageControllerExtension